defconfig: inline: Don't build generic synaptics ts driver
1. They're useless in samsung phone
2. Causing linking issue

ld.lld: error: duplicate symbol: response_complete
>>> defined in drivers/built-in.a(input/touchscreen/synaptics_tcm/synaptics_tcm_core.o)
>>> defined in drivers/built-in.a(input/touchscreen/ovt/td4150_spi/ovt_tcm_core.o)

ld.lld: error: duplicate symbol: zeroflash_remove_complete
>>> defined in drivers/built-in.a(input/touchscreen/synaptics_tcm/synaptics_tcm_zeroflash.o)
>>> defined in drivers/built-in.a(input/touchscreen/ovt/td4150_spi/ovt_tcm_zeroflash.o)
make[1]: *** [/home/runner/work/Builder/Builder/kernel_root/Makefile:1200: vmlinux] Error 1

Signed-off-by: rsuntk <rissu.ntk@gmail.com>